routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','HomeController@index')->name('accueil');
Route::get('publications/type/{slug}','PublicationsController@index')->name('publications.type');
Route::get('publications/arrondissement/{slug}','PublicationsController@arrondissement')->name('publications.arrondissement');
Route::get('publications/all','PublicationsController@index')->name('publications');
Route::get('publications/{slug}','PublicationsController@details')->name('publications.details');
Route::get('publications/type/{type}','PublicationsController@index')->name('publications.type');
Route::get('publications/zone/{zone}','PublicationsController@zone')->name('publications.zone');
Route::get('publications/quartier/{quartier}','PublicationsController@quartier')->name('publications.quartier');
Route::get('publications/arrondissement/{arrondissement}','PublicationsController@arrondissement')->name('publications.arrondissement');
Route::get('ajax/newpub','HomeController@newpub')->name('ajax.newpub');
Route::get('ajax/newevents','HomeController@newevents')->name('ajax.newevents');
Route::get('ajax/newlois','HomeController@newlois')->name('ajax.newlois');

Route::get('evenements','EvenementController@index')->name('evenements');
Route::get('evenements/{slug}','EvenementController@index')->name('evenements.type');
Route::get('evenements/arrondissement/{slug}','EvenementController@arrondissement')->name('evenements.arrondissement');

Route::get('leslois','LoiController@index')->name('lois');
Route::get('leslois/{slug}','LoiController@index')->name('lois.type');
Route::get('leslois/arrondissement/{slug}','LoiController@arrondissement')->name('lois.arrondissement');

Route::get('dashboard','DashboardController@index')->name('dashboard')->middleware('auth');

Auth::routes();

Route::post('inscription','InscriptionController@inscription')->name('inscription');

Route::group(['middleware'=> ['auth']],function (){
    Route::get('publications/{id}/like','PublicationsController@add')->name('publications.like');
    Route::post('commentaire/{id}','CommentaireController@store')->name('commentaire.store');
    Route::get('dashboard/voscommentaires','CommentaireController@voscommentaires')->name('voscommentaires');
    Route::post('dashboard/voscommentaires/delete/{id}','CommentaireController@destroy')->name('voscommentaires.delete');
    Route::get('dashboard/commentaires','CommentaireController@commentaires')->name('commentaires')->middleware('checkadmin');
    Route::post('dashboard/commentaires/delete/{id}','CommentaireController@destroy')->name('commentaires.delete')->middleware('checkadmin');
});

Route::group(['as'=>'dashboard.','prefix'=>'dashboard','namespace'=>'dashboard','middleware'=>['auth','dashboard']], function (){

    Route::resource('typeevenement','TypeevenementController')->middleware('checkadmin');
    Route::resource('typepublication','TypesPublicationController')->middleware('checkadmin');
    Route::resource('typeloi','TypeloiController')->middleware('checkadmin');
    Route::resource('arrondissement','ArrondissementController')->middleware('checkadmin');
    Route::resource('quartier','QuartierController')->middleware('checkadmin');
    Route::resource('zone','ZoneController')->middleware('checkadmin');
    Route::resource('publication','PublicationController')->middleware('checkadmin');
    Route::resource('loi','LoiController')->middleware('checkadmin');
    Route::resource('voslois','VosloiController')->middleware('checkrespoadmin');
    Route::resource('utilisateurs','UtilisateurController')->middleware('checkadmin');
    //Route::resource('evenement','EvenementController')->middleware('checknotcitoyen');
    //Route::resource('vospublication','VospublicationController');

    Route::get('/evenements','EvenementController@index')->name('evenements')->middleware('checknotcitoyen');
    Route::get('/evenements/create','EvenementController@create')->name('evenements.create')->middleware('checkassociation');
    Route::post('/evenements/store','EvenementController@store')->name('evenements.store')->middleware('checkassociation');
    Route::get('/evenements/edit/{id}','EvenementController@edit')->name('evenements.edit')->middleware('checkassorespo');
    Route::post('/evenements/update/{id}','EvenementController@update')->name('evenements.update')->middleware('checkassorespo');
    Route::post('/evenements/delete/{id}','EvenementController@destroy')->name('evenements.delete')->middleware('checkassoadmin');

    Route::get('/vospublications','VospublicationController@index')->name('vospublications');
    Route::get('/vospublications/create','VospublicationController@create')->name('vospublications.create');
    Route::post('/vospublications/store','VospublicationController@store')->name('vospublications.store');
    Route::get('/vospublications/edit/{id}','VospublicationController@edit')->name('vospublications.edit');
    Route::post('/vospublications/update/{id}','VospublicationController@update')->name('vospublications.update');
    Route::post('/vospublications/delete/{id}','VospublicationController@destroy')->name('vospublications.delete');

    Route::get('parametres','ParametreController@index')->name('parametres');
    Route::put('parametres/update','ParametreController@update')->name('parametres.update');
    Route::put('parametres/change','ParametreController@change')->name('parametres.change');

    Route::get('favoris','LikesController@index')->name('favoris');

});

app/Http/Controllers/Dashboard/ArrondissementController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Arrondissement;
use App\Utilisateur;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ArrondissementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $arrondissements = Arrondissement::orderBy('name','asc')->get();
        return view('dashboard.arrondissement.index',compact('arrondissements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $users = Utilisateur::all()->where('role_id','=','2');
        return view('dashboard.arrondissement.create',compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'name' => 'required',
        ]);
        $arrondissement = new Arrondissement();
        $arrondissement->name = $request->name;
        $arrondissement->responsable_id = $request->responsable_id;
        $arrondissement->slug = str_slug($request->name);
        $arrondissement->save();
        Toastr::success('Arrondissement bien enregistré', 'Succès');
        return redirect()->route('dashboard.arrondissement.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $arrondissement = Arrondissement::find($id);
        $users = Utilisateur::all()->where('role_id','=','2');
        return view('dashboard.arrondissement.edit', compact('arrondissement','users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[
            'name' => 'required',
        ]);

        $arrondissement = Arrondissement::find($id);
        $arrondissement->name = $request->name;
        $arrondissement->responsable_id = $request->responsable_id;
        $arrondissement->slug = str_slug($request->name);
        $arrondissement->save();

        Toastr::success('Arrondissement bien modifié', 'Succès');
        return redirect()->route('dashboard.arrondissement.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Arrondissement::find($id)->delete();
        Toastr::success('Arrondissement bien supprimé', 'Succès');
        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/EvenementController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Arrondissement;
use App\Evenement;
use App\Typeevenement;
use App\Zone;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class EvenementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $evenements = Evenement::latest()->get();
        return view('dashboard/evenement/index',compact('evenements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $zones = Zone::all()->sortBy('quartier_id');
        $arrondissements = Arrondissement::all();
        $types = Typeevenement::all()->sortBy('name');
        return view('dashboard/evenement/create',compact('zones','arrondissements','types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[
            'titre' => 'required|max:100',
            'description' => 'required',
            'typeevenement_id' => 'required',
            'zone_id' => 'required',
            'datedebut' => 'required',
            'datefin' => 'required',
        ]);

        $evenement = new Evenement();

        $evenement->titre = $request->titre;
        $evenement->description = $request->description;
        $evenement->typeevenement_id=$request->typeevenement_id;
        $evenement->zone_id=$request->zone_id;
        $evenement->datedebut=$request->datedebut;
        $evenement->datefin=$request->datefin;
        $evenement->utilisateur_id=Auth::id();
        $evenement->save();
        Toastr::success('Evenement bien enregistrée.', 'Succès');
        return redirect()->route('dashboard.evenements');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //

        $evenement = Evenement::find($id);
        $zones = Zone::all()->sortBy('quartier_id');
        $arrondissements = Arrondissement::all();
        $types = Typeevenement::all();
        return view('dashboard/evenement/edit',compact('evenement','zones','types','arrondissements'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        //dd($request);
        if(Auth::user()->role_id!=2){
            $this->validate($request,[
                'titre' => 'required|max:100',
                'description' => 'required',
                'typeevenement_id' => 'required',
                'zone_id' => 'required',
                'datedebut' => 'required',
                'datefin' => 'required',
            ]);
        }

        $evenement = Evenement::find($id);
        if(Auth::user()->role_id==2 && $request->status!=""){
            $evenement->status=$request->status;
        }else{
            $evenement->titre = $request->titre;
            $evenement->description = $request->description;
            $evenement->typeevenement_id=$request->typeevenement_id;
            $evenement->zone_id=$request->zone_id;
            $evenement->datedebut=$request->datedebut;
            $evenement->datefin=$request->datefin;
        }
        $evenement->save();
        Toastr::success('Evenement bien enregistrée.', 'Succès');
        return redirect()->route('dashboard.evenements');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $evenement = Evenement::find($id);
        $evenement->forceDelete();

        Toastr::success('Evenement bien supprimée.', 'Succès');
        return redirect()->route('evenements');
    }
}

app/Http/Controllers/Dashboard/LikesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class LikesController extends Controller
{
    //
    public function index(){
        $publications = Auth::user()->like_publications;
        return view('dashboard.favoris.index',compact('publications'));
    }
}

app/Http/Controllers/Dashboard/ParametreController.php
<?php

namespace App\Http\Controllers\dashboard;

use App\Utilisateur;
use Brian2694\Toastr\Facades\Toastr;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class ParametreController extends Controller
{
    //
    public function index(){
        return view('dashboard.parametres.index');
    }

    public function update(Request $request){
        if(Auth::user()->role_id != 3||Auth::user()->role_id != 2){
            $this->validate($request,[
                'name' => 'required',
            ]);
            if(Auth::user()->email!=$request->email){
                $this->validate($request,[
                    'email' => 'required|unique:utilisateurs|email',
                ]);
            }
            if(Auth::user()->username!=$request->username){
                $this->validate($request,[
                    'username' => 'required|unique:utilisateurs|min:5',
                ]);
            }
        }
        $this->validate($request,[
            'image' => 'mimes:jpeg,png,jpg',
            'telephone' => 'required|numeric|min:11',
            'about' => 'required|min:10',
        ]);

        $user = Utilisateur::find(Auth::id());
        $image = $request->file('image');
        if(isset($image)){
            $filename = time().'.'.strtolower($image->getClientOriginalExtension());

            if(isset($user->image) && File::exists(public_path($user->image))){
                unlink(public_path($user->image));
            }
            $image->move('profils',$filename);
            $filename = 'profils/'.$filename;
            $user->image = $filename;
        }

        if(Auth::user()->role_id != 3) {
            $user->name = $request->name;
            $user->email = $request->email;
        }

        $user->username = $request->username;
        $user->telephone = $request->telephone;
        $user->about = $request->about;
        $user->save();

        Toastr::success('Votre compte a été mise à jour.','Succès');
        return redirect()->back();

    }

    public function change(Request $request){
        $this->validate($request,[
            'mdpold' => 'required',
            'mdpnew' => 'required|min:6',
            'confirm_mdpnew' => 'required|min:6',
        ]);
        if($request->mdpnew == $request->confirm_mdpnew){
            if(Hash::check($request->mdpold,Auth::user()->password)){
                if(!Hash::check($request->mdpnew,Auth::user()->password)){
                    $user = Utilisateur::find(Auth::id());
                    $user->password = Hash::make($request->mdpnew);
                    $user->save();
                    Toastr::success('Votre mot de passe a été mis à jour.','Succès');
                    Auth::logout();
                    return redirect()->back();
                }else{
                    Toastr::error("Le nouveau mot de passe ne peut pas etre le meme que l'ancien",'Echec');
                    return redirect()->back();
                }
            }else{
                Toastr::error("L'ancien mot de passe n'est pas exact.",'Echec');
                return redirect()->back();
            }
        }else{
            Toastr::error("La confirmation et le nouveau mot de passe ne sont pas conformes.",'Echec');
            return redirect()->back();
        }

        Toastr::success('Votre mot de passe a été changé.','Succès');
        return redirect()->back();
    }
}

resources/views/dashboard/publication/create.blade.php
@extends('layouts.backend.app')

@section('title','Nouvelle publication')

@push('css')

    <!-- Bootstrap Select Css -->
    <link href="{{asset('assets/backend/plugins/bootstrap-select/css/bootstrap-select.css')}}" rel="stylesheet" />

@endpush


@section('content')
    <div class="container-fluid">
        <form action="{{route('dashboard.publication.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
            <!-- Vertical Layout -->
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                FAIRE UNE NOUVELLE PUBLICATION
                            </h2>
                        </div>
                        <div class="body">

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" id="name" class="form-control" name="titre">
                                    <label class="form-label">Titre de la publication</label>
                                </div>
                            </div>

                            <span>Contenu de votre publication</span>
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <textarea type="text" id="tinymce" class="form-control" name="contenu"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                INFORMATION
                            </h2>
                        </div>
                        <div class="body">
                            <div class="form-group bootstrap-select form-control show-tick">
                                <select class="form-control show-tick" name="typePublication_id">
                                    <option value="0">Choisir le type de publication</option>
                                    @foreach($types as $type)
                                        <option value="{{$type->id}}">{{$type->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <br>
                            <div class="form-group bootstrap-select form-control show-tick">
                                <select class="form-control show-tick" name="zone_id">
                                    <option value="0">Choisir la zone</option>
                                    @foreach($arrondissements as $arrondissement)
                                        <optgroup label="{{$arrondissement->name}}">
                                            @foreach($zones as $zone)
                                                @if($zone->quartier->arrondissement->name == $arrondissement->name)
                                                    <option value="{{$zone->id}}">{{$zone->name}}\{{$zone->quartier->name}}</option>
                                                @endif
                                            @endforeach
                                        </optgroup>
                                    @endforeach
                                </select>
                            </div>
                            <br>
                            <div class="form-group">
                                <label for="media">Joindre un fichier</label>
                                <input type="file" name="media">
                            </div>

                            <a class="btn btn-danger m-t-15 waves-effect" href="{{route('dashboard.publication.index')}}">RETOUR</a>
                            <button type="submit" class="btn btn-primary m-t-15 waves-effect">ENREGISTRER</button>
                        </div>
                    </div>
                </div>
            </div>

        </form>
    </div>


@endsection


@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/tinymce/tinymce.js')}}"></script>
    <!-- Select Plugin Js -->
    <script src="{{asset('assets/backend/plugins/bootstrap-select/js/bootstrap-select.js')}}"></script>

    <script>
        $(function () {
            //TinyMCE
            tinymce.init({
                selector: "textarea#tinymce",
                theme: "modern",
                height: 300,
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true
            });
            tinymce.suffix = ".min";
            tinyMCE.baseURL = '{{asset('assets/backend/plugins/tinymce')}}';
        });
    </script>

@endpush

resources/views/dashboard/publication/index.blade.php
@extends('layouts.backend.app')

@section('title','Publications')

@push('css')
    <!-- JQuery DataTable Css -->
    <link href="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css')}}" rel="stylesheet">
@endpush


@section('content')
    <div class="container-fluid">
            <div class="block-header">
                <a class="btn btn-primary waves-effect" href="{{route('dashboard.publication.create')}}">
                    <i class="material-icons">add</i>
                    <span>Nouvelle Publication</span>
                </a>
            </div>
            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                TOUTES LES PUBLICATIONS
                                <span class="badge bg-blue">{{$publications->count()}}</span>
                            </h2>

                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>MEDIA</th>
                                        <th>TITRE</th>
                                        <th>AUTEUR</th>
                                        <th>LIEU</th>
                                        <th>TYPE</th>
                                        <th>ACTION</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>ID</th>
                                        <th>MEDIA</th>
                                        <th>TITRE</th>
                                        <th>AUTEUR</th>
                                        <th>LIEU</th>
                                        <th>TYPE</th>
                                        <th>ACTION</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>

                                        @foreach($publications as $key=>$publication)
                                            <tr>
                                                <td>{{$key + 1}}</td>
                                                <td align="center">
                                                    @if($publication->mediaurl)
                                                        @if(str_contains($publication->mediaurl,['jpeg','jpg','png']))
                                                            <img src="{{asset($publication->mediaurl)}}" width="50" height="50"/>
                                                        @elseif(str_contains($publication->mediaurl,['avi','mp4','flv']))
                                                            <video src="{{asset($publication->mediaurl)}}" width="50" height="50" controls/>
                                                        @endif
                                                    @endif
                                                </td>
                                                <td>{{$publication->titre}}</td>
                                                <td>{{$publication->utilisateur->name}}</td>
                                                <td>

                                                    @if($publication->quartier_id==0 && $publication->zone_id==0 && $publication->arrondissement_id==0)

                                                    @else
                                                        {{$publication->zone->name}}<br>{{$publication->zone->quartier->name}}<br>{{$publication->zone->quartier->arrondissement->name}}
                                                    @endif

                                                </td>
                                                <td>{{$publication->typepublication->name}}</td>
                                                <td class="text-center">
                                                    <a class="btn btn-info waves-effect" href="{{route('dashboard.publication.edit',$publication->id)}}">
                                                        <i class="material-icons">edit</i>

                                                    </a>

                                                    <button class="btn btn-danger waves-effect"
                                                            onclick="deletePublication({{$publication->id}})"
                                                            Publication="button">
                                                        <i class="material-icons">delete</i>
                                                    </button>

                                                    <form method="post" id="delete-form-{{$publication->id}}" action="{{route('dashboard.publication.destroy',$publication->id)}}" style="display: none;">
                                                        @csrf
                                                        @method('DELETE')
                                                    </form>

                                                </td>
                                            </tr>
                                        @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
@endsection


@push('js')
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{asset('assets/backend/plugins/jquery-datatable/jquery.dataTables.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.flash.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/jszip.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/pdfmake.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/vfs_fonts.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.html5.min.js')}}"></script>
    <script src="{{asset('assets/backend/plugins/jquery-datatable/extensions/export/buttons.print.min.js')}}"></script>
    <script src="{{asset('assets/backend/js/pages/tables/jquery-datatable.js')}}"></script>

    <script src="https://unpkg.com/sweetalert@2.1.0/dist/sweetalert.min.js"></script>

    <script Publication="text/javascript">
        function deletePublication(id) {
            swal({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this imaginary file!",
                icon: "warning",
                confirmButtonText: 'Oui, supprimer ce Publication!',
                cancelButtonText: 'Non, annuler!',
                cancelButtonClass: 'btn btn-danger',
                confirmButtonClass:'btn btn-success',
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        event.preventDefault();
                        document.getElementById('delete-form-'+id).submit();
                        swal("Poof! Your imaginary file has been deleted!", {
                            icon: "success",
                        });
                    } else {
                        swal('Cancelled',
                            "Your imaginary file is safe!",
                            'error');
                    }
                });
        }

    </script>

@endpush